// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo7DLN2icPTSPwMWwwESxd02IMDPzUGiI',
    appId: '1:953552026191:web:f0acd0d4d12e067c92083a',
    messagingSenderId: '953552026191',
    projectId: 'test-task-auth-58701',
    authDomain: 'test-task-auth-58701.firebaseapp.com',
    storageBucket: 'test-task-auth-58701.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfA8YgaDtI3IEyJrnDJqPsLW9DDUw9Bw4',
    appId: '1:953552026191:android:d19da60e5f436dda92083a',
    messagingSenderId: '953552026191',
    projectId: 'test-task-auth-58701',
    storageBucket: 'test-task-auth-58701.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8PeWmk0eOUMAtwaqlEFBy-f-wRKeg1L0',
    appId: '1:953552026191:ios:d0ae464501ddffcd92083a',
    messagingSenderId: '953552026191',
    projectId: 'test-task-auth-58701',
    storageBucket: 'test-task-auth-58701.appspot.com',
    iosBundleId: 'com.example.firebase2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8PeWmk0eOUMAtwaqlEFBy-f-wRKeg1L0',
    appId: '1:953552026191:ios:c3424cdfc0a806f192083a',
    messagingSenderId: '953552026191',
    projectId: 'test-task-auth-58701',
    storageBucket: 'test-task-auth-58701.appspot.com',
    iosBundleId: 'com.example.firebase2.RunnerTests',
  );
}
